{{- if .Values.clusterCloudflareProvider.enabled }}
{{- $provider := .Values.clusterCloudflareProvider }}
apiVersion: kflared.kodeblox.com/v1alpha1
kind: ClusterCloudflareProvider
metadata:
  name: {{ default (include "kflared.fullname" .) $provider.name }}
  labels:
    {{- include "kflared.labels" . | nindent 4 }}
spec:
  controller: {{ required "controllerClass is required when clusterCloudflareProvider.enabled=true" .Values.controllerClass | quote }}
  accountID: {{ required "clusterCloudflareProvider.accountID is required when clusterCloudflareProvider.enabled=true" $provider.accountID | quote }}
  apiTokenSecretRef:
    name: {{ default (include "kflared.secretName" .) $provider.apiTokenSecretRef.name | quote }}
    key: {{ required "clusterCloudflareProvider.apiTokenSecretRef.key is required when clusterCloudflareProvider.enabled=true" $provider.apiTokenSecretRef.key | quote }}
  allowedDNSZones:
    {{- $provider.allowedDNSZones | toYaml | nindent 4 }}
  bindingNamespaceSelector:
    {{- $provider.bindingNamespaceSelector | toYaml | nindent 4 }}
{{- end }}
