{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kflared.fullname" . }}-manager
  labels:
    {{- include "kflared.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["namespaces", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kflared.kodeblox.com"]
    resources: ["clustercloudflareproviders", "cloudflaretunnelbindings", "cloudflaretunnelprivateroutes"]
    verbs: ["get", "list", "update", "watch"]
  - apiGroups: ["kflared.kodeblox.com"]
    resources: ["clustercloudflareproviders/finalizers", "cloudflaretunnelbindings/finalizers", "cloudflaretunnelprivateroutes/finalizers"]
    verbs: ["update"]
  - apiGroups: ["kflared.kodeblox.com"]
    resources: ["clustercloudflareproviders/status", "cloudflaretunnelbindings/status", "cloudflaretunnelprivateroutes/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints"]
    verbs: ["create", "delete", "get", "patch", "update"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses", "gateways", "httproutes", "referencegrants"]
    verbs: ["get", "list", "watch"]
{{- if and .Values.metrics.enabled .Values.metrics.secure }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kflared.fullname" . }}-metrics-auth
  labels:
    {{- include "kflared.labels" . | nindent 4 }}
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kflared.fullname" . }}-metrics-reader
  labels:
    {{- include "kflared.labels" . | nindent 4 }}
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
{{- end }}
{{- end }}
