{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kflared.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kflared.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: {{ ternary "https" "http" .Values.metrics.secure }}
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "kflared.selectorLabels" . | nindent 4 }}
{{- end }}
