apiVersion: kflared.kodeblox.com/v1alpha1
kind: CloudflareTunnelBinding
metadata:
  labels:
    app.kubernetes.io/name: kflared
    app.kubernetes.io/managed-by: kustomize
  name: public
  namespace: my-app
spec:
  controller: kflared
  providerRef:
    name: default
  gatewayRef:
    name: traefik
    sectionName: http
  originServiceRef:
    name: traefik-cloudflare
    namespace: traefik
    port: cloudflare
  connectorReplicas: 2
  dnsAutomationEnabled: true
  deletionPolicy: Delete
