## Append samples of your project ##
resources:
- gateway_v1_referencegrant.yaml
- kflared_v1alpha1_cloudflaretunnelbinding.yaml
- kflared_v1alpha1_clustercloudflareprovider.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
