//go:build !ignore_autogenerated

/*
Copyright 2026 Sayak Mukhopadhyay.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelBinding) DeepCopyInto(out *CloudflareTunnelBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelBinding.
func (in *CloudflareTunnelBinding) DeepCopy() *CloudflareTunnelBinding {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnelBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelBindingList) DeepCopyInto(out *CloudflareTunnelBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareTunnelBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelBindingList.
func (in *CloudflareTunnelBindingList) DeepCopy() *CloudflareTunnelBindingList {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnelBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelBindingSpec) DeepCopyInto(out *CloudflareTunnelBindingSpec) {
	*out = *in
	out.ProviderRef = in.ProviderRef
	out.GatewayRef = in.GatewayRef
	out.OriginServiceRef = in.OriginServiceRef
	if in.DNSAutomationEnabled != nil {
		in, out := &in.DNSAutomationEnabled, &out.DNSAutomationEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelBindingSpec.
func (in *CloudflareTunnelBindingSpec) DeepCopy() *CloudflareTunnelBindingSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelBindingStatus) DeepCopyInto(out *CloudflareTunnelBindingStatus) {
	*out = *in
	if in.PublishedHostnames != nil {
		in, out := &in.PublishedHostnames, &out.PublishedHostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DNSRecords != nil {
		in, out := &in.DNSRecords, &out.DNSRecords
		*out = make([]DNSRecord, len(*in))
		copy(*out, *in)
	}
	out.Resources = in.Resources
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelBindingStatus.
func (in *CloudflareTunnelBindingStatus) DeepCopy() *CloudflareTunnelBindingStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCloudflareProvider) DeepCopyInto(out *ClusterCloudflareProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCloudflareProvider.
func (in *ClusterCloudflareProvider) DeepCopy() *ClusterCloudflareProvider {
	if in == nil {
		return nil
	}
	out := new(ClusterCloudflareProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCloudflareProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCloudflareProviderList) DeepCopyInto(out *ClusterCloudflareProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterCloudflareProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCloudflareProviderList.
func (in *ClusterCloudflareProviderList) DeepCopy() *ClusterCloudflareProviderList {
	if in == nil {
		return nil
	}
	out := new(ClusterCloudflareProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCloudflareProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCloudflareProviderSpec) DeepCopyInto(out *ClusterCloudflareProviderSpec) {
	*out = *in
	out.APITokenSecretRef = in.APITokenSecretRef
	if in.AllowedDNSZones != nil {
		in, out := &in.AllowedDNSZones, &out.AllowedDNSZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.BindingNamespaceSelector.DeepCopyInto(&out.BindingNamespaceSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCloudflareProviderSpec.
func (in *ClusterCloudflareProviderSpec) DeepCopy() *ClusterCloudflareProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterCloudflareProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCloudflareProviderStatus) DeepCopyInto(out *ClusterCloudflareProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCloudflareProviderStatus.
func (in *ClusterCloudflareProviderStatus) DeepCopy() *ClusterCloudflareProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCloudflareProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorResourceNames) DeepCopyInto(out *ConnectorResourceNames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorResourceNames.
func (in *ConnectorResourceNames) DeepCopy() *ConnectorResourceNames {
	if in == nil {
		return nil
	}
	out := new(ConnectorResourceNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecord) DeepCopyInto(out *DNSRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecord.
func (in *DNSRecord) DeepCopy() *DNSRecord {
	if in == nil {
		return nil
	}
	out := new(DNSRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayReference) DeepCopyInto(out *GatewayReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayReference.
func (in *GatewayReference) DeepCopy() *GatewayReference {
	if in == nil {
		return nil
	}
	out := new(GatewayReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalReference) DeepCopyInto(out *LocalReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalReference.
func (in *LocalReference) DeepCopy() *LocalReference {
	if in == nil {
		return nil
	}
	out := new(LocalReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginServiceReference) DeepCopyInto(out *OriginServiceReference) {
	*out = *in
	out.Port = in.Port
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginServiceReference.
func (in *OriginServiceReference) DeepCopy() *OriginServiceReference {
	if in == nil {
		return nil
	}
	out := new(OriginServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}
